package com.healthcoco.healthcocopad.enums;

/**
 * Created by Prashant on 13/03/2018.
 */

public enum AdapterType {

    APOINTMENT_QUEUE, DOCTOR_POPUP_LIST, EVENT_LIST, KIOSK_SUB_ITEM, ABOUT_DOCTOR, CLINIC_IMAGE,VACCINATION, SEARCH_VACCINATION,
    UPDATE_VACCINE, UPDATE_BRAND, BRAND_LIST, SELECTED_BRAND, GROWTH_CHART, BABY_ACHIEVEMENTS;
}
