package com.healthcoco.healthcocopad.enums;

/**
 * Created by Prashant on 13/03/2018.
 */

public enum AdapterType {

    APOINTMENT_QUEUE, DOCTOR_POPUP_LIST, EVENT_LIST, KIOSK_SUB_ITEM, ABOUT_DOCTOR,
    CLINIC_IMAGE, FOOD_SUB_ITEM, RECIPE_ITEM, INGREDIENT_ITEM, RECIPE_ITEM_SOLR,
    NUTRIENT_ITEM, EQUIVALENT_MEASUREMENT, INGREDIENT_ITEM_SOLR;
}
