package com.healthcoco.healthcocoplus.enums;

/**
 * Created by Shreshtha on 24-01-2017.
 */

public enum AutoCompleteTextViewType {
    COMPLAINT, OBSERVATION, INVESTIGATION, DIAGNOSIS, NOTE,
    YEAR_OF_PASSING, EXPERIENCE_LIST, BLOOD_GROUP, PROFESSION, COUNTRY, AVAILABLE_BOOKED_APPOINTMENTS, NUMBERS, DRUG_TYPE, DOCTOR_TITLES, DIAGNOSTIC_TEST, ROLES, CITY, DOCTOR_CLINIC, APPOINTMENT_SLOT
}
