package com.healthcoco.healthcocoplus.enums;

/**
 * Created by Shreshtha on 24-01-2017.
 */
public enum LocalBackgroundTaskType {
    ADD_PATIENTS, GET_PATIENTS,
    CLEAR_PATIENTS, ADD_TEMPLATES, ADD_DRUGS_LIST, ADD_RECORDS, ADD_CLINAL_NOTE,
    ADD_GROUPS_LIST, ADD_COMPLAINT, ADD_OBSERVATION, ADD_HISTORY_LIST, ADD_DISEASE_LIST,
    ADD_MEDICAL_HISTORY, ADD_VISITS, ADD_DURATION_UNIT, ADD_DRUG_DOSAGE, ADD_DIRECTIONS,
    ADD_DRUG_TYPE, ADD_SPECIALITIES, ADD_CITIES, ADD_BLOOD_GROUPS, ADD_PROFESSION,
    ADD_REFERENCE, GET_CITIES, GET_BLOOD_GROUP,
    ADD_PRESCRIPTION, GET_REFERENCE_HIDDEN_LIST, GET_REFERENCE_ACTIVATED_LIST,
    GET_REFERENCE_LIST_ALL,
    GET_DIRECTION_HIDDEN_LIST, GET_DIRECTION_ACTIVATED_LIST,
    GET_HISTORY_HIDDEN_LIST, GET_HISTORY_ACTIVATED_LIST,
    GET_FREQUENCY_HIDDEN_LIST, GET_FREQUENCY_ACTIVATED_LIST,
    GET_DRUG_HIDDEN_LIST, GET_DRUG_ACTIVATED_LIST,
    GET_GROUPS, GET_DISEASE_HIDDEN_LIST, GET_DISEASE_ACTIVATED_LIST,
    GET_PROFESSION_LIST, GET_VISITS, GET_MEDICAL_AND_FAMILY_HISTORY,
    GET_HISTORY_LIST, GET_DISEASE_LIST, GET_RECORDS, GET_CLINICAL_NOTES,
    ADD_LOCATION, GET_LOCATION, ADD_EDUCATION_QUALIFICATION, ADD_MEDICAL_COUNCILS,
    ADD_INSTITUTES, GET_DOCTOR_PROFILE, ADD_DOCTOR_PROFILE, GET_SPECIALITIES,
    GET_DURATION_UNIT, GET_TEMPLATES_LIST, GET_FRAGMENT_INITIALISATION_DATA,
    GET_DIAGRAMS, ADD_DIAGRAMS, GET_PRESCRIPTION,
    ADD_COMPLAINT_SUGGESTIONS, ADD_OBSERVATION_SUGGESTIONS,
    ADD_INVESTIGATION_SUGGESTIONS, ADD_DIAGNOSIS_SUGGESTIONS,
    GET_COMPLAINT_SUGGESTIONS, GET_OBSERVATION_SUGGESTIONS, GET_INVESTIGATION_SUGGESTIONS, SEARCH_PATIENTS, GET_DIAGNOSIS_SUGGESTIONS,
    SORT_LIST_BY_GROUP, SORT_LIST_BY_RECENTLY_VISITED, SORT_LIST_BY_MOSTLY_VISITED, GET_VISIT_DETAILS, DELETE_GROUP, GET_APPOINTMENTS, ADD_APPOINTMENTS, ADD_CALENDAR_EVENTS, GET_CALENDAR_EVENTS, SORT_LIST_BY_RECENTLY_ADDED
}
