package com.healthcoco.healthcocopad.enums;

/**
 * Created by Shreshtha on 24-01-2017.
 */

public enum AutoCompleteTextViewType {
    COMPLAINT, OBSERVATION, INVESTIGATION, DIAGNOSIS, NOTE,
    HISTORY_OF_PRESENT_COMPLAINT,
    MENSTRUAL_HISTORY,
    OBSTETRIC_HISTORY,
    GENERAL_EXAMINATION,
    SYSTEMIC_EXAMINATION,
    PROVISIONAL_DIAGNOSIS,
    ECG_DETAILS,
    ECHO,
    X_RAY_DETAILS,
    HOLTER,
    PA,
    PV,
    PS,
    INDICATION_OF_USG,ADVANCE_SEARCH_OPTION,
    YEAR_OF_PASSING, EXPERIENCE_LIST, BLOOD_GROUP, PROFESSION, COUNTRY, AVAILABLE_BOOKED_APPOINTMENTS, NUMBERS, DRUG_TYPE, DOCTOR_TITLES, DIAGNOSTIC_TEST, ROLES, CITY, DOCTOR_CLINIC, REFERENCE, PRESENT_COMPLAINT, APPOINTMENT_SLOT
}
