package com.healthcoco.healthcocopad.enums;

/**
 * Created by Shreshtha on 24-01-2017.
 */
public enum LocalTabelType {
    CITIES, SPECIALITIES, DRUG_DOSAGE, DRUG_DURATION_UNIT, DRUG_DIRECTION, STRENGTH_UNIT, REGISTERED_PATIENTS_DETAILS, USER_GROUP, COMPLAINT, OBSERVATION, INVESTIGATION, DIAGNOSIS, REFERENCE, DISEASE, TEMP_DRUG, RECORDS, TEMPLATE, COMPLAINT_SUGGESTIONS, OBSERVATION_SUGGESTIONS, INVESTIGATION_SUGGESTIONS, DIAGNOSIS_SUGGESTIONS, DRUG_TYPE, PROFESSION, HISTORY_DETAIL_RESPONSE;
}
