package com.healthcoco.healthcocopad.utilities;

/**
 * Created by Shreshtha on 20-01-2017.
 */
public class HealthCocoConstants {
    public static final String NO_NAME_FLAG = "#";
    public static final String TAG_DOCTOR_USER_ID = "doctorUserId";
    public static final String PARAM_IS_MOBILE_APP = "&isMobileApp=true";
    public static final String TAG_IS_FROM_LOGIN_SIGNUP = "isFromLoginSignUp";
    public static final String TAG_BROADCAST_EXTRA = "broadcastExtra";
    public static final String TAG_FRAGMENT_NAME = "fragmentName";
    public static final String TAG_EMAIL_ID = "emailId";
    public static final String TAG_COMMON_OPENUP_INTENT_DATA = "intentData";
    public static final String TAG_TOTAL_SYNC_SERVICES = "maxProgressValue";
    public static final String TAG_SYNC_SERVICE_TYPE = "syncServiceType";
    public static final String TAG_CLINIC_PROFILE = "clinicProfile";
    public static final String TAG_DOCTOR_PROFILE = "doctorProfile";
    public static final String TAG_UNIQUE_ID = "uniqueId";
    public static final String TAG_NAME_EDIT_TYPE = "nameEditDeleteType";
    public static final String TAG_ORDINAL = "ordinal";
    public static final String TAG_GROUP_ID = "group_id";
    public static final String TAG_GROUP_IDS_LIST = "groupsIdsList";
    public static final String TAG_IS_EDIT_PATIENT = "isEditPatient";
    public static final String TAG_TOOTH_NUMBER = "toothNumber";
    public static final String TAG_TOOTH_MATERIAL = "material";
    public static final String PARAM_TAG_UPDATE = "/update/";
    public static final String PARAM_TAG_GENERATE = "/generate/";
    public static final String PARAM_TAG_VERIFY = "/verify/";
    public static final String PARAM_CHANGE_STATE = "/changeState";
    public static final String PARAM_TAG_ADD = "/add/";
    public static final String TAG_DIAGRAM_TAG = "diagramTag";
    public static final String TAG_SELECTED_DIAGRAM = "selectedDiagram";
    public static final String TAG_MAP_TYPE = "mapType";

    public static final String TAG_INTENT_DATA = "intentData";
    public static final String TAG_PATIENT_PROFILE = "patientProfile";
    public static final String TAG_SELECTED_DATE_TIME_IN_MILLIS = "selectedTimeInMillis";
    public static final String TAG_DIAGNOSTICS_LIST = "diagnostics_list";
    public static final int RESULT_CODE_ADD_PRESCIPTION = 101;
    public static final int REQUEST_CODE_CAMERA = 102;
    public static final int REQUEST_CODE_GALLERY = 103;
    public static final int REQUEST_CODE_MENU_CLINIC_LIST = 105;
    public static final int RESULT_CODE_ADD_EDIT_CLINIC_ADDRESS = 106;
    public static final int RESULT_CODE_ADD_EDIT_CLINIC_HOURS = 107;
    public static final int RESULT_CODE_ADD_EDIT_CLINIC_CONTACT = 108;
    public static final int RESULT_CODE_ADD_EDIT_APPOINTMENT_DETAILS = 109;
    public static final int RESULT_CODE_DOCTOR_PROFESSIONAL_MEMBERSHIP_DETAIL = 110;
    public static final int RESULT_CODE_DOCTOR_PROFESSIONAL_STATEMENT_DETAIL = 111;
    public static final int REQUEST_CODE_REFERENCE_LIST = 112;
    public static final int RESULT_CODE_REFERENCE_LIST = 113;
    public static final int REQUEST_CODE_GLOBAL_RECORDS_ACCESS = 114;
    public static final int RESULT_CODE_GLOBAL_RECORDS_ACCESS = 115;
    public static final int REQUEST_CODE_VERIFY_OTP = 116;
    public static final int REQUEST_CODE_TREATMENT = 195;
    public static final int RESULT_CODE_SELECTED_TREATMENT = 199;
    public static final int REQUEST_CODE_ADD_TREATMENT = 200;
    public static final int RESULT_CODE_ADD_NEW_TREATMENT = 206;
    public static final int RESULT_CODE_VERIFY_OTP = 117;
    public static final int RESULT_CODE_DOCTOR_PERSONAL_HISTORY_DETAIL = 142;
    public static final int RESULT_CODE_DRUGS_AND_ALLERGIES_DETAIL = 143;
    public static final int RESULT_CODE_CONTINUE_SIGNUP = 144;
    public static final int RESULT_CODE_DIAGRAM_DETAIL = 145;
    public static final int RESULT_CODE_ADD_NEW_TEMPLATE = 146;
    public static final int RESULT_CODE_ADD_VISIT = 147;
    public static final int RESULT_CODE_GROUPS_LIST = 124;
    public static final int RESULT_CODE_SEARCH_NUMBER_RESULTS = 125;
    public static final int REQUEST_CODE_GROUPS_LIST = 126;
    public static final int RESULT_CODE_ADD_GROUP = 127;
    public static final int RESULT_CODE_REGISTRATION = 128;
    public static final int RESULT_CODE_ADD_STRING = 132;
    public static final int RESULT_CODE_DISEASE_LIST = 135;
    public static final int REQUEST_CODE_ADD_CLINICAL_NOTES = 136;
    public static final int RESULT_CODE_BOOK_APPOINTMENT = 148;
    public static final int RESULT_CODE_DIAGNOSTICS_TESTS = 149;
    public static final String PARAM_SIZE = "&size=";
    public static final String PARAM_PAGE = "&page=";
    public static final String PARAM_SEARCH_TERM = "&searchTerm=";
    public static final String PARAM_PAGE_AND = "&page=";
    public static final String PARAM_SPECIALITY = "?speciality=";
    public static final String PARAM_DISCARDED_FALSE = "discarded=false";
    public static final int RESULT_CODE_NEXT_REVIEW = 150;
    public static final int RESULT_CODE_ADD_CLINICAL_NOTE = 151;
    public static final String TAG_TAB_TYPE = "tabType";
    public static final int RESULT_CODE_DOCTOR_PROFILE_CONTACT = 152;
    public static final int RESULT_CODE_AWARDS_AND_PUNLICATION = 153;
    public static final int RESULT_CODE_EDUCATIONAL_DETAIL = 154;
    public static final int RESULT_CODE_EXPERIENCE_DETAIL = 155;
    public static final int RESULT_CODE_REGISTRATION_DETAIL = 156;
    public static final int RESULT_CODE_ADD_EDIT_DOCTOR_PROFILE = 157;
    public static final int REQUEST_CODE_FILE = 158;
    public static final String PARAM_UPDATED_TIME = "&updatedTime=";
    public static final String PARAM_DISCARDED_AMPERCENT = "&discarded=";
    public static final String PARAM_DOCTOR_ID = "&doctorId=";
    public static final String PARAM_DISCARDED_TRUE = "?discarded=true";
    public static final String PARAM_HOSPITAL_ID = "&hospitalId=";
    public static final String PARAM_LOCATION_ID = "&locationId=";
    public static final String PARAM_TAG_VIEW = "/view/?";
    public static final String PARAM_ROLE = "&role=";
    public static final String TAG_SELECTED_USER_ID = "selectedPatientId";
    public static final String TAG_MOBILE_NUMBER = "mobileNo";
    public static final String PARAM_TAG_DELETE = "/delete/";
    public static final String TAG_ORDINAL_DIALOG_TYPE = "dialogTypeOrdinal";
    public static final String TAG_ORDINAL_WEB_SERVICE_TYPE = "webServiceTypeOrdinal";
    public static final String TAG_HISTORY_FILTER_TYPE = "historyFilterType";
    public static final String TAG_DISEASE_IDS_LIST = "diseaseIdsList";
    public static final String PARAM_PATIENT_ID = "&patientId=";
    public static final String PARAM_TAG_SMS = "/sms/";
    public static final String PARAM_TAG_MAIL = "/mail/";
    public static final String TAG_VISIT_ID = "visitId";
    public static final String TAG_IS_FROM_CLONE = "isFromClone";
    public static final String TAG_IS_FROM_VISIT = "isFromVisit";
    public static final String TAG_PRESCRIPTION_ID = "prescriptionId";
    public static final String TAG_TEMPLATE_ID = "templateId";
    public static final String TAG_DRUG_DETAILS = "drugDetails";
    public static final String TAG_IS_FROM_NEW_TEMPLATE_FRAGMENT = "isFromNewtemplateFragment";
    public static boolean isNetworkOnline;
    public static String SELECTED_PATIENTS_USER_ID = null;
    public static String VISIT_ID_TO_SEND = null;
    public static String VISIT_ID_CLINICAL_NOTES = null;
    public static String VISIT_ID_REPORTS = null;
    public static String VISIT_ID_PRESCRIPTION = null;
    public static String VISIT_ID_TREATMENT = null;

}
